// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1719688183);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1719687853);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1719687856);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1719688040);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1719687973);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1719688062);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1719687886);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1719688303);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 8953);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1719687823);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d898c551-998c-4dba-aaea-1f8526b4e132}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1719687921690");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1719689711690");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1719687850137");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1719709450137");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.slowStartup.averageTime", 8100);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1719688035);
user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"user-agent-switcher_ninetailed_ninja-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"user-agent-switcher_ninetailed_ninja-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":3}");
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1719687845065");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "2f9706deab854fa1ae58e63f74a184c0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1719688185);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200708170202");
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.user-agent-switcher@ninetailed.ninja", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e27b7087-6898-4b11-a7a3-60f92a692963\",\"formautofill@mozilla.org\":\"5404818e-c09b-41d3-9172-9cc98c429676\",\"screenshots@mozilla.org\":\"a9900a1e-d03a-4906-8041-74e4e103cbb9\",\"webcompat-reporter@mozilla.org\":\"6fbed6fd-d5c3-4cbd-8bb7-0a91fb8462b5\",\"webcompat@mozilla.org\":\"7bef6eab-4be8-4c83-98bc-b9d61e4945ad\",\"default-theme@mozilla.org\":\"ddc77146-e9f1-4c85-a6d1-603771cb9de3\",\"google@search.mozilla.org\":\"f72d4352-bae1-4107-a7a6-b8e29d08dd93\",\"amazondotcom@search.mozilla.org\":\"d533ae84-2070-42e0-a485-a11fbae3b6c5\",\"bing@search.mozilla.org\":\"3a4aa39a-3c9f-4f21-94ed-49abf58a7642\",\"ddg@search.mozilla.org\":\"aa68f595-6a56-48cf-a426-0bf1d40a0aa6\",\"ebay@search.mozilla.org\":\"957756cd-b8c5-4c0f-b9e3-0155381a0110\",\"wikipedia@search.mozilla.org\":\"61c2e79f-c5f1-4d3b-a055-6e13ae5c7344\",\"firefox-compact-dark@mozilla.org\":\"acf97188-7135-446d-9b20-18f36014e24e\",\"firefox-compact-light@mozilla.org\":\"f6c46297-fd1d-469f-ac41-b1ca572cb88e\",\"user-agent-switcher@ninetailed.ninja\":\"0ceab652-8f51-4d81-969c-d4b8d303ce7a\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.benchmark.vp9.fps", 32);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-manager.buildID", "20200708170202");
user_pref("media.gmp-manager.lastCheck", 1719688205);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 53789);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.blocklist.addons.checked", 1719688061);
user_pref("services.blocklist.gfx.checked", 1719688061);
user_pref("services.blocklist.plugins.checked", 1719688061);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1719676630945\"");
user_pref("services.settings.last_update_seconds", 1719688061);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1719688061);
user_pref("services.settings.main.cfr.last_check", 1719688061);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1719688061);
user_pref("services.settings.main.hijack-blocklists.last_check", 1719688061);
user_pref("services.settings.main.language-dictionaries.last_check", 1719688061);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1719688061);
user_pref("services.settings.main.search-config.last_check", 1719688061);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1719688061);
user_pref("services.settings.main.sites-classification.last_check", 1719688061);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1719688061);
user_pref("services.settings.main.whats-new-panel.last_check", 1719688061);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1719688029);
user_pref("toolkit.telemetry.cachedClientID", "a6363c6f-57f8-4fe7-a605-035832d64f39");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
